[#patterns-datataskpublisher-trymap]
== Stricter request processing with dataTaskPublisher

__Goal__::

* When URLSession makes a connection, it only reports an error if the remote server doesn't respond. You may want to consider a number of responses, based on status code, to be errors. To accomplish this, you can use tryMap to inspect the http response and throw an error in the pipeline.

__References__::

* <<reference#reference-datataskpublisher,URLSession.dataTaskPublisher>>
* <<reference#reference-trymap,tryMap>>
* <<reference#reference-decode,decode>>
* <<reference#reference-sink,sink>>
* <<reference#reference-subscribe,subscribe>>

__See also__::

* <<patterns#patterns-datataskpublisher-decode,Making a network request with dataTaskPublisher>>
* <<patterns#patterns-oneshot-error-handling,Using catch to handle errors in a one-shot pipeline>>
* <<patterns#patterns-retry,Retrying in the event of a temporary failure>>


__Code and explanation__::

To have more control over what is considered a failure in the URL response, use a `tryMap` operator on the tuple response from dataTaskPublisher.
Since dataTaskPublisher returns both the response data and the URLResponse into the pipeline, you can immediately inspect the response and throw an error of your own if desired.

An example of that might look like:

[source, swift]
----
let myURL = URL(string: "https://postman-echo.com/time/valid?timestamp=2016-10-10")
// checks the validity of a timestamp - this one returns {"valid":true}
// matching the data structure returned from https://postman-echo.com/time/valid
fileprivate struct PostmanEchoTimeStampCheckResponse: Decodable, Hashable {
    let valid: Bool
}
enum testFailureCondition: Error {
    case invalidServerResponse
}


let remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: myURL!)
    .tryMap { data, response -> Data in <1>
                guard let httpResponse = response as? HTTPURLResponse, <2>
                    httpResponse.statusCode == 200 else { <3>
                        throw testFailureCondition.invalidServerResponse <4>
                }
                return data <5>
    }
    .decode(type: PostmanEchoTimeStampCheckResponse.self, decoder: JSONDecoder())

let cancellableSink = remoteDataPublisher
    .sink(receiveCompletion: { completion in
            print(".sink() received the completion", String(describing: completion))
            switch completion {
                case .finished:
                    break
                case .failure(let anError):
                    print("received error: ", anError)
            }
    }, receiveValue: { someValue in
        print(".sink() received \(someValue)")
    })
----

Where the <<patterns#patterns-datataskpublisher-decode, previous pattern>> used a <<reference#reference-map,map>> operator, this uses tryMap, which allows us to identify and throw errors in the pipeline based on what was returned.

<1> <<reference#reference-trymap,tryMap>> still gets the tuple of `(data: Data, response: URLResponse)`, and is defined here as returning just the type of Data down the pipeline.
<2> Within the closure for tryMap, we can cast the response to HTTPURLResponse and dig deeper into it, including looking at the specific status code.
<3> In this case, we want to consider **anything** other than a 200 response code as a failure. HTTPURLResponse.status_code is an Int type, so you could also have logic such as `httpResponse.statusCode > 300`.
<4> If the predicates aren't met, then we can throw an instance of an error of our choosing, `invalidServerResponse` in this case.
<5> If no error has occured, then we simply pass down Data for further processing.

When an error is triggered on the pipeline, a `.failure` completion is sent with the error encapsulated within it, regardless of where it happened in the pipeline.

// force a page break - in HTML rendering is just a <HR>
<<<
'''
